language: groovy
jdk:
- openjdk7
script: ./grailsw refresh-dependencies
  && ./grailsw "test-app unit:"
cache:
  directories:
  - "$HOME/.grails"
  - "$HOME/.ivy2"
notifications:
  slack:
    secure: NJ2bhtLK2Xn0vPfq/lAxehuwLshp50Uep1mHMTbiQ7WK/YxNhLbrjgIbh9ZcM/UxZ4AhYX3Wv4VUI9iyEa06XUNTtxaM3ia8Eqao1wTVMl9N0RvU+VgHINORmyZZlf4MNBOZItwsmZT2b094gAfPIg7r8VuCo1wVqGjubVfTeUQ=
